function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
  }

export const getCurrent = function(city: string) {
    return {
        "coord":{"lon":-0.13,"lat":51.51},
        "weather":[{"id":300,"main":"Drizzle","description":"light intensity drizzle","icon":"09d"}],
        "base":"stations",
        "main":{"temp":getRandomInt(-20, 20),"pressure":getRandomInt(700,1000),"humidity":getRandomInt(30, 100),"temp_min":getRandomInt(-30, 0),"temp_max":getRandomInt(20, 40)},
        "visibility":getRandomInt(0, 10000),
        "wind":{"speed":getRandomInt(0, 10),"deg":80},
        "clouds":{"all":90},
        "dt":1485789600,
        "sys":{"type":1,"id":5091,"message":0.0103,"country":"GB","sunrise":1485762037,"sunset":1485794875},
        "id":2643743,
        "name":city,
        "cod":200};
}

export const getHourly = function(city: string) {
    const time = new Date();
    const times = [];
    for (let i = 0; i < 24; i++) {
        time.setHours(time.getHours() + 1);
        times.push(`${time.getDate().toLocaleString()}.${time.getMonth().toLocaleString()} ${time.getHours().toLocaleString()}:00`);
    }
    const temp = getRandomInt(-20, 20);
    const temp_min = getRandomInt(-30, 0);
    const temp_max = getRandomInt(20, 40);
    const pressure = getRandomInt(700,1000);
    const humidity = getRandomInt(30, 100);
    const speed = getRandomInt(0, 10);

    return {
        "cod":"200",
        "message":0.0204,
        "cnt":96,
        "list":[
            {"dt":1553709600,
            "main":{"temp":temp,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1018.01,"grnd_level":997.153,"humidity":humidity,"temp_kf":0.73},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":60},
            "wind":{"speed":speed,"deg":287.822},
            "sys":{"pod":"n"},
            "dt_txt": times[0]},
            {"dt":1553713200,
            "main":{"temp":temp,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-3,"sea_level":1018.335,"grnd_level":997.403,"humidity":humidity-2,"temp_kf":0.49},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"02n"}],
            "clouds":{"all":2},
            "wind":{"speed":speed+1,"deg":294.075},
            "sys":{"pod":"n"},
            "dt_txt":times[1]},
            {"dt":1553716800,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-2,"sea_level":1018.794,"grnd_level":997.864,"humidity":humidity-2,"temp_kf":0.24},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
            "clouds":{"all":1},
            "wind":{"speed":speed+1,"deg":300.189},
            "sys":{"pod":"n"},
            "dt_txt":times[2]},
            {"dt":1553720400,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-3,"sea_level":1019.211,"grnd_level":998.29,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
            "clouds":{"all":1},
            "wind":{"speed":speed,"deg":305.558},
            "sys":{"pod":"n"},
            "dt_txt":times[3]},
            {"dt":1553724000,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure+1,"sea_level":1019.58,"grnd_level":998.674,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
            "clouds":{"all":1},
            "wind":{"speed":speed,"deg":309.126},
            "sys":{"pod":"n"},
            "dt_txt":times[4]},
            {"dt":1553727600,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure+2,"sea_level":1019.849,"grnd_level":998.886,"humidity":humidity-3,"temp_kf":0},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],
            "clouds":{"all":0},
            "wind":{"speed":speed+2,"deg":307.204},
            "sys":{"pod":"n"},
            "dt_txt":times[5]},
            {"dt":1553731200,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure+2,"sea_level":1020.021,"grnd_level":998.983,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"02n"}],
            "clouds":{"all":7},
            "wind":{"speed":speed,"deg":304.735},
            "sys":{"pod":"n"},
            "dt_txt":times[6]},
            {"dt":1553734800,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure+3,"sea_level":1020.24,"grnd_level":999.091,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":66},
            "wind":{"speed":speed+3,"deg":306.38},
            "sys":{"pod":"n"},
            "dt_txt":times[7]},
            {"dt":1553738400,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1020.634,"grnd_level":999.451,"humidity":humidity-4,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":67},
            "wind":{"speed":speed+4,"deg":313.941},
            "sys":{"pod":"n"},
            "dt_txt":times[8]},
            {"dt":1553742000,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-5,"sea_level":1021.2,"grnd_level":1000.078,"humidity":humidity-5,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":78},
            "wind":{"speed":speed+2,"deg":323.001},
            "sys":{"pod":"n"},
            "dt_txt":times[9]},
            {"dt":1553745600,
            "main":{"temp":temp+3,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-5,"sea_level":1021.887,"grnd_level":1000.825,"humidity":humidity-5,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],
            "clouds":{"all":83},
            "wind":{"speed":speed,"deg":325.587},
            "sys":{"pod":"d"},
            "dt_txt":times[10]},
            {"dt":1553749200,
            "main":{"temp":temp+3,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-5,"sea_level":1022.26,"grnd_level":1001.249,"humidity":humidity-6,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":86},
            "wind":{"speed":speed,"deg":325.37},
            "sys":{"pod":"d"},
            "dt_txt":times[11]},
            {"dt":1553752800,
            "main":{"temp":temp+3,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-6,"sea_level":1022.629,"grnd_level":1001.705,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":86},
            "wind":{"speed":speed,"deg":327.239},
            "sys":{"pod":"d"},
            "dt_txt":times[12]},
            {"dt":1553756400,
            "main":{"temp":temp+4,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-7,"sea_level":1023.002,"grnd_level":1002.215,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":96},
            "wind":{"speed":speed+1,"deg":329.474},
            "sys":{"pod":"d"},
            "dt_txt":times[13]},
            {"dt":1553760000,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-7,"sea_level":1023.327,"grnd_level":1002.643,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":95},
            "wind":{"speed":speed+1,"deg":331.284},
            "sys":{"pod":"d"},
            "dt_txt":times[14]},
            {"dt":1553763600,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-5,"sea_level":1023.522,"grnd_level":1002.861,"humidity":humidity-3,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":94},
            "wind":{"speed":speed,"deg":331.928},
            "sys":{"pod":"d"},
            "dt_txt":times[15]},
            {"dt":1553767200,
            "main":{"temp":temp+2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-6,"sea_level":1023.577,"grnd_level":1002.923,"humidity":humidity-10,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":94},
            "wind":{"speed":speed,"deg":332.483},
            "sys":{"pod":"d"},
            "dt_txt":times[16]},
            {"dt":1553770800,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-3,"sea_level":1023.539,"grnd_level":1002.905,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":94},
            "wind":{"speed":speed-1,"deg":332.007},
            "sys":{"pod":"d"},
            "dt_txt":times[17]},
            {"dt":1553774400,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-2,"sea_level":1023.439,"grnd_level":1002.827,"humidity":humidity-5,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":94},
            "wind":{"speed":speed+2,"deg":330.692},
            "sys":{"pod":"d"},
            "dt_txt":times[18]},
            {"dt":1553778000,
            "main":{"temp":temp+1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure-1,"sea_level":1023.462,"grnd_level":1002.794,"humidity":humidity-3,"temp_kf":0},
            "weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],
            "clouds":{"all":85},
            "wind":{"speed":speed+2,"deg":330.72},
            "sys":{"pod":"d"},
            "dt_txt":times[19]},
            {"dt":1553781600,
            "main":{"temp":temp,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1023.597,"grnd_level":1002.933,"humidity":humidity,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],
            "clouds":{"all":65},
            "wind":{"speed":speed,"deg":328.604},
            "sys":{"pod":"d"},
            "dt_txt":times[20]},
            {"dt":1553785200,
            "main":{"temp":temp-1,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1023.736,"grnd_level":1003.062,"humidity":humidity-2,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],
            "clouds":{"all":74},
            "wind":{"speed":speed-2,"deg":320.741},
            "sys":{"pod":"d"},
            "dt_txt":times[21]},
            {"dt":1553788800,
            "main":{"temp":temp-2,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1023.865,"grnd_level":1003.222,"humidity":humidity-3,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":57},
            "wind":{"speed":speed-3,"deg":311.882},
            "sys":{"pod":"n"},
            "dt_txt":times[22]},
            {"dt":1553792400,
            "main":{"temp":temp-3,"temp_min":temp_min,"temp_max":temp_max,"pressure":pressure,"sea_level":1024.036,"grnd_level":1003.379,"humidity":humidity-10,"temp_kf":0},
            "weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],
            "clouds":{"all":57},
            "wind":{"speed":speed,"deg":304.168},
            "sys":{"pod":"n"},
            "dt_txt":times[23]}        
        ],
        "city":{"id":524901,"name":city,"coord":{"lat":55.7522,"lon":37.6156},"country":"RU"}
    };
}

export const getDays = function(city: string) {
    const temp = getRandomInt(-20, 20);
    const temp_day = temp+10;
    const temp_night = temp-10;
    const temp_morn = temp+2;
    const temp_eve = temp-1;
    const pressure = getRandomInt(700,1000);
    const humidity = getRandomInt(30, 100);
    const speed = getRandomInt(0, 10);
    return {
        "cod":"200",
        "message":0,
        "city":{"geoname_id":524901,"name":city,"lat":55.7522,"lon":37.6156,"country":"RU","iso2":"RU","type":"city","population":0},
        "cnt":7,
        "list":[
            {"dt":1485766800,
            "temp":{"day":temp_day,"min":261.41,"max":262.65,"night":temp_night,"eve":temp_eve,"morn":temp_morn},
            "pressure":pressure,
            "humidity":humidity,
            "weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01d"}],
            "speed":speed,
            "deg":225,
            "clouds":0,
            "snow":0.01},
            {"dt":1485853200,
            "temp":{"day":temp_day+1,"min":260.98,"max":265.44,"night":temp_night-3,"eve":temp_eve+1,"morn":temp_morn+3},
            "pressure":pressure+2,
            "humidity":humidity+7,
            "weather":[{"id":600,"main":"Snow","description":"light snow","icon":"13d"}],
            "speed":speed+3,
            "deg":249,
            "clouds":88,
            "snow":1.44},
            {"dt":1485939600,
            "temp":{"day":temp_day+2,"min":266.9,"max":270.59,"night":temp_night+4,"eve":temp_eve+6,"morn":temp_morn+1},
            "pressure":pressure-2,
            "humidity":humidity+11,
            "weather":[{"id":600,"main":"Snow","description":"light snow","icon":"13d"}],
            "speed":speed-2,
            "deg":298,
            "clouds":64,
            "snow":0.92},
            {"dt":1486026000,
            "temp":{"day":temp_day+10,"min":255.19,"max":264.02,"night":temp_night-4,"eve":temp_eve-1,"morn":temp_morn+6},
            "pressure":pressure-1,
            "humidity":humidity-1,
            "weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01d"}],
            "speed":speed+4,
            "deg":344,
            "clouds":0},
            {"dt":1486112400,
            "temp":{"day":temp_day+5,"min":256.55,"max":266,"night":temp_night+2,"eve":temp_eve-3,"morn":temp_morn-3},
            "pressure":pressure+10,
            "humidity":humidity-10,
            "weather":[{"id":600,"main":"Snow","description":"light snow","icon":"13d"}],
            "speed":speed+6,
            "deg":24,
            "clouds":45,
            "snow":0.21},
            {"dt":1486198800,
            "temp":{"day":temp_day+1,"min":254.73,"max":259.95,"night":temp_night-3,"eve":temp_eve+3,"morn":temp_morn-2},
            "pressure":pressure-20,
            "humidity":humidity-2,
            "weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01d"}],
            "speed":speed-3,
            "deg":331,
            "clouds":29},
            {"dt":1486285200,
            "temp":{"day":temp_day+5,"min":259.11,"max":263.13,"night":temp_night,"eve":temp_eve,"morn":temp_morn+3},
            "pressure":pressure,
            "humidity":humidity,
            "weather":[{"id":600,"main":"Snow","description":"light snow","icon":"13d"}],
            "speed":speed,
            "deg":234,
            "clouds":46,
            "snow":0.04}]};
}